export const SELECT_PAYMENT_METHOD = "SELECT_PAYMENT_METHOD";
export const TOGGLE_GIFT_STATUS = "TOGGLE_GIFT_STATUS";
export const SELECT_PRICE_PER_TIME = "SELECT_PRICE_PER_TIME";
export const TOGGLE_AUTOPAY_STATUS = "TOGGLE_AUTOPAY_STATUS";
export const TOGGLE_DISCOUNT_STATUS = "TOGGLE_DISCOUNT_STATUS";
export const UPDATE_TOTAL_PRICE = "UPDATE_TOTAL_PRICE";
